import type { Condition, Game, Setup } from "@/lib/types";

export const setups: Setup[] = [
  {
    id: "1",
    game: "iRacing",
    car: "Porsche 992 GT3 Cup",
    track: "Spa-Francorchamps",
    condition: "Dry",
    lapTime: "2:16.482",
    description:
      "Stable rear end through Eau Rouge with a touch more front splitter for confidence on entry. Great for long stints.",
    tags: ["Safe", "Race"],
    rigProfile: "Direct Drive + Load Cell",
    author: "MikaR33",
    uploadedAt: "2026-06-28",
    upvotes: 214,
    pace: 4,
    predictability: 5,
    downloads: 1820,
  },
  {
    id: "2",
    game: "ACC",
    car: "Ferrari 296 GT3",
    track: "Monza",
    condition: "Dry",
    lapTime: "1:47.312",
    description:
      "Low drag qualifying setup, max top speed down the straights. Twitchy on cold tires so build up to the limit.",
    tags: ["Quali", "Aggressive"],
    rigProfile: "Wheel + 3 Pedals",
    author: "ScuderiaSim",
    uploadedAt: "2026-06-30",
    upvotes: 358,
    pace: 5,
    predictability: 2,
    downloads: 2650,
  },
  {
    id: "3",
    game: "F1 24",
    car: "F1 2024 Car",
    track: "Silverstone",
    condition: "Mixed",
    lapTime: "1:26.104",
    description:
      "Balanced downforce for the fast flowing sections, softened rear anti-roll bar to handle changing grip levels.",
    tags: ["Race", "Wet Weather"],
    rigProfile: "Wheel + Handbrake",
    author: "PitwallPete",
    uploadedAt: "2026-06-25",
    upvotes: 132,
    pace: 4,
    predictability: 4,
    downloads: 940,
  },
  {
    id: "4",
    game: "rFactor 2",
    car: "BMW M4 GT3",
    track: "Nürburgring GP",
    condition: "Dry",
    lapTime: "1:52.771",
    description:
      "Beginner friendly setup with softer springs and extra ride height for the kerbs. Forgiving under braking.",
    tags: ["Beginner", "Safe"],
    rigProfile: "Gamepad",
    author: "NordschleifeNoob",
    uploadedAt: "2026-06-20",
    upvotes: 89,
    pace: 3,
    predictability: 5,
    downloads: 610,
  },
  {
    id: "5",
    game: "iRacing",
    car: "Dallara IR-18",
    track: "Road America",
    condition: "Dry",
    lapTime: "2:04.998",
    description:
      "High-speed stability build for the oval-adjacent kink. Slightly loose on exit to rotate faster mid-corner.",
    tags: ["Race", "Aggressive"],
    rigProfile: "Direct Drive + Load Cell",
    author: "OvalToRoad",
    uploadedAt: "2026-06-29",
    upvotes: 176,
    pace: 5,
    predictability: 3,
    downloads: 1210,
  },
  {
    id: "6",
    game: "ACC",
    car: "Audi R8 LMS Evo II",
    track: "Spa-Francorchamps",
    condition: "Wet",
    lapTime: "2:31.640",
    description:
      "Full wet tune with taller gearing for standing water and extra front wing to keep the nose planted at Eau Rouge.",
    tags: ["Wet Weather", "Safe"],
    rigProfile: "Wheel + 3 Pedals",
    author: "RainMaster",
    uploadedAt: "2026-06-27",
    upvotes: 261,
    pace: 4,
    predictability: 4,
    downloads: 1590,
  },
  {
    id: "7",
    game: "Automobilista 2",
    car: "Formula Ultimate",
    track: "Interlagos",
    condition: "Dry",
    lapTime: "1:38.220",
    description:
      "Aggressive qualifying trim, minimum downforce for the back straight. Requires precise inputs through Senna S.",
    tags: ["Quali", "Aggressive"],
    rigProfile: "Direct Drive + Load Cell",
    author: "InterlagosAce",
    uploadedAt: "2026-06-22",
    upvotes: 97,
    pace: 5,
    predictability: 2,
    downloads: 505,
  },
  {
    id: "8",
    game: "Gran Turismo 7",
    car: "Mazda MX-5 Cup",
    track: "Suzuka",
    condition: "Dry",
    lapTime: "2:02.410",
    description:
      "Simple, planted setup for newcomers to the track. Predictable rotation through the Esses with no snap oversteer.",
    tags: ["Beginner", "Safe"],
    rigProfile: "Gamepad",
    author: "TsukubaTom",
    uploadedAt: "2026-06-18",
    upvotes: 64,
    pace: 3,
    predictability: 5,
    downloads: 402,
  },
  {
    id: "9",
    game: "iRacing",
    car: "Mercedes AMG GT3",
    track: "Watkins Glen",
    condition: "Mixed",
    lapTime: "1:41.556",
    description:
      "Versatile setup for changeable conditions, medium downforce with a wet-ready alignment that still works in the dry.",
    tags: ["Race", "Safe"],
    rigProfile: "Wheel + 3 Pedals",
    author: "GlenGuru",
    uploadedAt: "2026-07-01",
    upvotes: 145,
    pace: 4,
    predictability: 4,
    downloads: 780,
  },
  {
    id: "10",
    game: "F1 24",
    car: "F1 2024 Car",
    track: "Monaco",
    condition: "Dry",
    lapTime: "1:12.037",
    description:
      "Max downforce street circuit tune. Short gearing for the tight hairpins, stiff front end for late braking into Turn 1.",
    tags: ["Quali", "Aggressive"],
    rigProfile: "Wheel + Handbrake",
    author: "MonteCarloMax",
    uploadedAt: "2026-06-24",
    upvotes: 289,
    pace: 5,
    predictability: 3,
    downloads: 2010,
  },
  {
    id: "11",
    game: "ACC",
    car: "Lamborghini Huracán GT3 Evo2",
    track: "Zandvoort",
    condition: "Dry",
    lapTime: "1:36.882",
    description:
      "Balanced race setup that manages tire wear over 40+ minute stints without losing rear stability in the banked final corner.",
    tags: ["Race", "Safe"],
    rigProfile: "Direct Drive + Load Cell",
    author: "DuneRacer",
    uploadedAt: "2026-06-15",
    upvotes: 121,
    pace: 4,
    predictability: 4,
    downloads: 655,
  },
  {
    id: "12",
    game: "rFactor 2",
    car: "Porsche 992 GT3 Cup",
    track: "Sebring",
    condition: "Dry",
    lapTime: "2:01.933",
    description:
      "Beginner-safe ride height and soft compression to absorb the bumps without unsettling the car through the infield.",
    tags: ["Beginner", "Safe"],
    rigProfile: "Wheel + 3 Pedals",
    author: "FloridaFlyer",
    uploadedAt: "2026-06-12",
    upvotes: 58,
    pace: 3,
    predictability: 5,
    downloads: 340,
  },
];

export const games: Game[] = [
  "iRacing",
  "ACC",
  "F1 24",
  "rFactor 2",
  "Automobilista 2",
  "Gran Turismo 7",
];

export const conditions: Condition[] = ["Dry", "Wet", "Mixed"];

export function getCarsForGame(game?: string) {
  const filtered = game ? setups.filter((s) => s.game === game) : setups;
  return Array.from(new Set(filtered.map((s) => s.car))).sort();
}

export function getTracksForGame(game?: string) {
  const filtered = game ? setups.filter((s) => s.game === game) : setups;
  return Array.from(new Set(filtered.map((s) => s.track))).sort();
}
