import type { Condition, Game, Setup } from "@/lib/types";

export const setups: Setup[] = [
  {
    id: "1",
    game: "iRacing",
    car: "Porsche 992 GT3 Cup",
    track: "Spa-Francorchamps",
    condition: "Dry",
    lapTime: "2:16.482",
    description:
      "Stable rear end through Eau Rouge with a touch more front splitter for confidence on entry. Great for long stints.",
    tags: ["Safe", "Race"],
    rigProfile: "Direct Drive + Load Cell",
    author: "MikaR33",
    uploadedAt: "2026-06-28",
    upvotes: 214,
    pace: 4,
    predictability: 5,
    downloads: 1820,
    setupValues: {
      frontTirePressure: "23.5 psi",
      rearTirePressure: "24.0 psi",
      frontCamber: "-3.2°",
      rearCamber: "-2.7°",
      frontArb: "3 clicks",
      rearArb: "4 clicks",
      frontRideHeight: "65 mm",
      rearRideHeight: "72 mm",
      frontAero: "3",
      rearAero: "5",
      diffPreload: "65 Nm",
      diffPower: "Fixed (GT3 homologated)",
      brakeBias: "56% front",
      finalDrive: "Long — Spa's straights",
    },
  },
  {
    id: "2",
    game: "Assetto Corsa Competizione",
    car: "Ferrari 296 GT3",
    track: "Monza",
    condition: "Dry",
    lapTime: "1:47.312",
    description:
      "Low drag qualifying setup, max top speed down the straights. Twitchy on cold tires so build up to the limit.",
    tags: ["Quali", "Aggressive"],
    rigProfile: "Wheel + 3 Pedals",
    author: "ScuderiaSim",
    uploadedAt: "2026-06-30",
    upvotes: 358,
    pace: 5,
    predictability: 2,
    downloads: 2650,
    setupValues: {
      frontTirePressure: "26.3 psi",
      rearTirePressure: "26.8 psi",
      frontCamber: "-4.3°",
      rearCamber: "-3.8°",
      frontArb: "2 clicks",
      rearArb: "2 clicks",
      frontRideHeight: "52 mm",
      rearRideHeight: "58 mm",
      frontAero: "1 (min downforce)",
      rearAero: "2",
      diffPreload: "40 Nm",
      diffPower: "Fixed (GT3 homologated)",
      brakeBias: "58% front",
      finalDrive: "Short — Monza top speed",
    },
  },
  {
    id: "3",
    game: "F1 24",
    car: "F1 2024 Car",
    track: "Silverstone",
    condition: "Mixed",
    lapTime: "1:26.104",
    description:
      "Balanced downforce for the fast flowing sections, softened rear anti-roll bar to handle changing grip levels.",
    tags: ["Race", "Wet Weather"],
    rigProfile: "Wheel + Handbrake",
    author: "PitwallPete",
    uploadedAt: "2026-06-25",
    upvotes: 132,
    pace: 4,
    predictability: 4,
    downloads: 940,
    setupValues: {
      frontTirePressure: "23.0 psi",
      rearTirePressure: "21.0 psi",
      frontCamber: "Fixed (not adjustable in-game)",
      rearCamber: "Fixed (not adjustable in-game)",
      frontArb: "6/11",
      rearArb: "5/11",
      frontRideHeight: "3/11",
      rearRideHeight: "4/11",
      frontAero: "26",
      rearAero: "16",
      diffPreload: "N/A",
      diffPower: "On 65% / Off 55%",
      brakeBias: "54% front",
      finalDrive: "Balanced for Copse/Maggotts-Becketts",
    },
  },
  {
    id: "4",
    game: "Le Mans Ultimate",
    car: "BMW M4 GT3",
    track: "Fuji Speedway",
    condition: "Dry",
    lapTime: "1:52.771",
    description:
      "Beginner friendly setup with softer springs and extra ride height for the kerbs. Forgiving under braking.",
    tags: ["Beginner", "Safe"],
    rigProfile: "Gamepad",
    author: "FujiFan",
    uploadedAt: "2026-06-20",
    upvotes: 89,
    pace: 3,
    predictability: 5,
    downloads: 610,
    setupValues: {
      frontTirePressure: "25.0 psi",
      rearTirePressure: "25.5 psi",
      frontCamber: "-3.0°",
      rearCamber: "-2.5°",
      frontArb: "1 click",
      rearArb: "2 clicks",
      frontRideHeight: "70 mm",
      rearRideHeight: "76 mm",
      frontAero: "3",
      rearAero: "4",
      diffPreload: "35 Nm",
      diffPower: "Fixed (GT3 homologated)",
      brakeBias: "53% front",
      finalDrive: "Medium — Fuji's back straight",
    },
  },
  {
    id: "5",
    game: "iRacing",
    car: "Dallara IR-18",
    track: "Road America",
    condition: "Dry",
    lapTime: "2:04.998",
    description:
      "High-speed stability build for the oval-adjacent kink. Slightly loose on exit to rotate faster mid-corner.",
    tags: ["Race", "Aggressive"],
    rigProfile: "Direct Drive + Load Cell",
    author: "OvalToRoad",
    uploadedAt: "2026-06-29",
    upvotes: 176,
    pace: 5,
    predictability: 3,
    downloads: 1210,
    setupValues: {
      frontTirePressure: "24.5 psi",
      rearTirePressure: "23.5 psi",
      frontCamber: "-3.8°",
      rearCamber: "-1.8°",
      frontArb: "5 clicks",
      rearArb: "3 clicks",
      frontRideHeight: "35 mm",
      rearRideHeight: "45 mm",
      frontAero: "P4 (low downforce)",
      rearAero: "P5",
      diffPreload: "80 Nm",
      diffPower: "45% / 30%",
      brakeBias: "52% front",
      finalDrive: "Short — Turn 5-6 exit",
    },
  },
  {
    id: "6",
    game: "Assetto Corsa Competizione",
    car: "Audi R8 LMS Evo II",
    track: "Spa-Francorchamps",
    condition: "Wet",
    lapTime: "2:31.640",
    description:
      "Full wet tune with taller gearing for standing water and extra front wing to keep the nose planted at Eau Rouge.",
    tags: ["Wet Weather", "Safe"],
    rigProfile: "Wheel + 3 Pedals",
    author: "RainMaster",
    uploadedAt: "2026-06-27",
    upvotes: 261,
    pace: 4,
    predictability: 4,
    downloads: 1590,
    setupValues: {
      frontTirePressure: "25.0 psi",
      rearTirePressure: "25.5 psi",
      frontCamber: "-2.8°",
      rearCamber: "-2.2°",
      frontArb: "1 click",
      rearArb: "2 clicks",
      frontRideHeight: "68 mm",
      rearRideHeight: "74 mm",
      frontAero: "5",
      rearAero: "6 (max wet wing)",
      diffPreload: "50 Nm",
      diffPower: "Fixed (GT3 homologated)",
      brakeBias: "55% front",
      finalDrive: "Tall — standing water on Kemmel",
    },
  },
  {
    id: "7",
    game: "Automobilista 2",
    car: "Formula Ultimate",
    track: "Interlagos",
    condition: "Dry",
    lapTime: "1:38.220",
    description:
      "Aggressive qualifying trim, minimum downforce for the back straight. Requires precise inputs through Senna S.",
    tags: ["Quali", "Aggressive"],
    rigProfile: "Direct Drive + Load Cell",
    author: "InterlagosAce",
    uploadedAt: "2026-06-22",
    upvotes: 97,
    pace: 5,
    predictability: 2,
    downloads: 505,
    setupValues: {
      frontTirePressure: "24.0 psi",
      rearTirePressure: "22.5 psi",
      frontCamber: "-3.5°",
      rearCamber: "-1.9°",
      frontArb: "6 clicks",
      rearArb: "4 clicks",
      frontRideHeight: "28 mm",
      rearRideHeight: "38 mm",
      frontAero: "2 (min front wing)",
      rearAero: "3",
      diffPreload: "70 Nm",
      diffPower: "On 60% / Off 40%",
      brakeBias: "58% front",
      finalDrive: "Long — back straight into Juncao",
    },
  },
  {
    id: "8",
    game: "Assetto Corsa",
    car: "Mazda MX-5 Cup",
    track: "Suzuka",
    condition: "Dry",
    lapTime: "2:02.410",
    description:
      "Simple, planted setup for newcomers to the track. Predictable rotation through the Esses with no snap oversteer.",
    tags: ["Beginner", "Safe"],
    rigProfile: "Gamepad",
    author: "TsukubaTom",
    uploadedAt: "2026-06-18",
    upvotes: 64,
    pace: 3,
    predictability: 5,
    downloads: 402,
    setupValues: {
      frontTirePressure: "30.0 psi",
      rearTirePressure: "29.0 psi",
      frontCamber: "-2.0°",
      rearCamber: "-1.5°",
      frontArb: "2 clicks (soft)",
      rearArb: "1 click",
      frontRideHeight: "90 mm",
      rearRideHeight: "95 mm",
      frontAero: "N/A (no wing)",
      rearAero: "N/A (no wing)",
      diffPreload: "25 Nm",
      diffPower: "Stock (one-make spec)",
      brakeBias: "60% front",
      finalDrive: "Stock",
    },
  },
  {
    id: "9",
    game: "iRacing",
    car: "Mercedes AMG GT3",
    track: "Watkins Glen",
    condition: "Mixed",
    lapTime: "1:41.556",
    description:
      "Versatile setup for changeable conditions, medium downforce with a wet-ready alignment that still works in the dry.",
    tags: ["Race", "Safe"],
    rigProfile: "Wheel + 3 Pedals",
    author: "GlenGuru",
    uploadedAt: "2026-07-01",
    upvotes: 145,
    pace: 4,
    predictability: 4,
    downloads: 780,
    setupValues: {
      frontTirePressure: "24.0 psi",
      rearTirePressure: "24.5 psi",
      frontCamber: "-3.0°",
      rearCamber: "-2.5°",
      frontArb: "3 clicks",
      rearArb: "3 clicks",
      frontRideHeight: "62 mm",
      rearRideHeight: "68 mm",
      frontAero: "4",
      rearAero: "4",
      diffPreload: "55 Nm",
      diffPower: "Fixed (GT3 homologated)",
      brakeBias: "55% front",
      finalDrive: "Balanced — the Boot section",
    },
  },
  {
    id: "10",
    game: "F1 24",
    car: "F1 2024 Car",
    track: "Monaco",
    condition: "Dry",
    lapTime: "1:12.037",
    description:
      "Max downforce street circuit tune. Short gearing for the tight hairpins, stiff front end for late braking into Turn 1.",
    tags: ["Quali", "Aggressive"],
    rigProfile: "Wheel + Handbrake",
    author: "MonteCarloMax",
    uploadedAt: "2026-06-24",
    upvotes: 289,
    pace: 5,
    predictability: 3,
    downloads: 2010,
    setupValues: {
      frontTirePressure: "24.5 psi",
      rearTirePressure: "23.0 psi",
      frontCamber: "Fixed (not adjustable in-game)",
      rearCamber: "Fixed (not adjustable in-game)",
      frontArb: "9/11",
      rearArb: "7/11",
      frontRideHeight: "1/11 (min)",
      rearRideHeight: "2/11",
      frontAero: "48 (max downforce)",
      rearAero: "50",
      diffPreload: "N/A",
      diffPower: "On 50% / Off 65%",
      brakeBias: "52% front",
      finalDrive: "Short — hairpin to hairpin",
    },
  },
  {
    id: "11",
    game: "Assetto Corsa Competizione",
    car: "Lamborghini Huracán GT3 Evo2",
    track: "Zandvoort",
    condition: "Dry",
    lapTime: "1:36.882",
    description:
      "Balanced race setup that manages tire wear over 40+ minute stints without losing rear stability in the banked final corner.",
    tags: ["Race", "Safe"],
    rigProfile: "Direct Drive + Load Cell",
    author: "DuneRacer",
    uploadedAt: "2026-06-15",
    upvotes: 121,
    pace: 4,
    predictability: 4,
    downloads: 655,
    setupValues: {
      frontTirePressure: "26.5 psi",
      rearTirePressure: "27.0 psi",
      frontCamber: "-3.6°",
      rearCamber: "-3.0°",
      frontArb: "3 clicks",
      rearArb: "3 clicks",
      frontRideHeight: "60 mm",
      rearRideHeight: "65 mm",
      frontAero: "4",
      rearAero: "4",
      diffPreload: "60 Nm",
      diffPower: "Fixed (GT3 homologated)",
      brakeBias: "56% front",
      finalDrive: "Balanced — banked final corner",
    },
  },
  {
    id: "12",
    game: "Le Mans Ultimate",
    car: "Porsche 911 GT3 R",
    track: "Sebring",
    condition: "Dry",
    lapTime: "2:01.933",
    description:
      "Beginner-safe ride height and soft compression to absorb the bumps without unsettling the car through the infield.",
    tags: ["Beginner", "Safe"],
    rigProfile: "Wheel + 3 Pedals",
    author: "FloridaFlyer",
    uploadedAt: "2026-06-12",
    upvotes: 58,
    pace: 3,
    predictability: 5,
    downloads: 340,
    setupValues: {
      frontTirePressure: "24.0 psi",
      rearTirePressure: "24.5 psi",
      frontCamber: "-2.8°",
      rearCamber: "-2.3°",
      frontArb: "1 click (soft)",
      rearArb: "2 clicks",
      frontRideHeight: "72 mm",
      rearRideHeight: "76 mm",
      frontAero: "4",
      rearAero: "5",
      diffPreload: "35 Nm",
      diffPower: "Fixed (GT3 homologated)",
      brakeBias: "54% front",
      finalDrive: "Medium — bumpy infield section",
    },
  },
];

export const games: Game[] = [
  "iRacing",
  "Assetto Corsa EVO",
  "Assetto Corsa Competizione",
  "Assetto Corsa",
  "Le Mans Ultimate",
  "Automobilista 2",
  "F1 24",
  "F1 23",
  "F1 22",
  "F1 21",
  "F1 2020",
  "F1 2019",
];

export const conditions: Condition[] = ["Dry", "Wet", "Mixed"];

export function getCarsForGame(game?: string) {
  const filtered = game ? setups.filter((s) => s.game === game) : setups;
  return Array.from(new Set(filtered.map((s) => s.car))).sort();
}

export function getTracksForGame(game?: string) {
  const filtered = game ? setups.filter((s) => s.game === game) : setups;
  return Array.from(new Set(filtered.map((s) => s.track))).sort();
}
